import { Head, Link, useForm } from '@inertiajs/react';
import { useState } from 'react';
import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { index, store, update, destroy, plans } from '@/routes/products';

type Price = { currency_id: string; billing_cycle: string; price: string; setup_fee: string };
type ProductData = { product_group_id: string; name: string; slug: string; description: string; type: string; billing_type: string; module: string; setup_mode: string; plan_id: string; app_server_id: string; is_active: boolean; is_visible: boolean; requires_domain: boolean; sort_order: number; pricing: Price[] };
type Product = Omit<ProductData, 'product_group_id' | 'pricing' | 'plan_id' | 'app_server_id'> & { id: number; product_group_id: number; module_settings: { plan_id?: number; app_server_id?: string }; pricing: (Omit<Price, 'currency_id'> & { currency_id: number })[] };
const selectClass = 'h-10 w-full rounded-md border bg-background px-3 text-sm';
const recurring = ['monthly', 'quarterly', 'semiannually', 'annually', 'biennially', 'triennially'];
const setupModes = [ ['after_payment', 'After first payment', 'Activate after the first invoice is paid.'], ['on_order', 'Immediately on order', 'Activates before payment. Only use this when you intentionally allow unpaid provisioning.'], ['on_accept', 'After staff accepts the order', 'Wait for an administrator to accept the order in Billing.'], ['manual', 'Manual provisioning only', 'Wait until an administrator explicitly starts activation.'] ];
export default function ProductEditor({ product, groups, currencies }: { product: Product | null; groups: { id: number; name: string }[]; currencies: { id: number; code: string }[] }) {
    const [tab, setTab] = useState('details');
    const [deleting, setDeleting] = useState(false);
    const [remotePlans, setRemotePlans] = useState<{ id: number; name: string }[]>([]);
    const [nextPage, setNextPage] = useState<number | null>(1);
    const [loading, setLoading] = useState(false);
    const [planError, setPlanError] = useState('');
    const form = useForm<ProductData>({ product_group_id: String(product?.product_group_id ?? groups[0]?.id ?? ''), name: product?.name ?? '', slug: product?.slug ?? '', description: product?.description ?? '', type: product?.type ?? 'shared_hosting', billing_type: product?.billing_type ?? 'recurring', module: product?.module ?? 'manual', setup_mode: product?.setup_mode ?? 'after_payment', plan_id: String(product?.module_settings?.plan_id ?? ''), app_server_id: product?.module_settings?.app_server_id ?? '', is_active: product?.is_active ?? true, is_visible: product?.is_visible ?? true, requires_domain: product?.requires_domain ?? true, sort_order: product?.sort_order ?? 0, pricing: product?.pricing.map(p => ({ ...p, currency_id: String(p.currency_id) })) ?? [{ currency_id: String(currencies[0]?.id ?? ''), billing_cycle: 'monthly', price: '0.00', setup_fee: '0.00' }] });
    const errors = form.errors as Record<string, string>;
    function setPrice(row: number, field: keyof Price, value: string) { form.setData('pricing', form.data.pricing.map((p, i) => i === row ? { ...p, [field]: value } : p)); }
    function paymentType(value: string) {
        let rows = form.data.pricing;
        if (value !== 'recurring') { rows = rows.filter((p, i) => rows.findIndex(other => other.currency_id === p.currency_id) === i).map(p => ({ ...p, billing_cycle: 'one_time', ...(value === 'free' ? { price: '0.00', setup_fee: '0.00' } : {}) })); }
        else { rows = rows.map(p => ({ ...p, billing_cycle: p.billing_cycle === 'one_time' ? 'monthly' : p.billing_cycle })); }
        form.setData({ ...form.data, billing_type: value, pricing: rows });
    }
    async function loadPlans() {
        setLoading(true); setPlanError('');
        try { const response = await fetch(plans.url({ query: { page: nextPage ?? 1 } }), { headers: { Accept: 'application/json' } }); const result = await response.json(); if (!response.ok) { throw new Error(result.message ?? 'Could not load plans.'); } setRemotePlans(current => [...current, ...result.plans]); setNextPage(result.next_page); }
        catch (error) { setPlanError(error instanceof Error ? error.message : 'Could not load plans.'); }
        finally { setLoading(false); }
    }
    return <><Head title={product ? `Edit ${product.name}` : 'Create product'} /><form onSubmit={event => { event.preventDefault(); if (product) { form.put(update.url(product.id)); } else { form.post(store.url()); } }} className="mx-auto w-full max-w-5xl space-y-6 p-6">
        <Link href={index()} className="text-sm text-muted-foreground hover:underline">← Products & services</Link>
        <header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold">{product ? product.name : 'Create product'}</h1><p className="mt-2 text-muted-foreground">Product details, pricing, and fulfillment in one place.</p></div><Button disabled={form.processing || groups.length === 0 || currencies.length === 0}>{form.processing ? 'Saving…' : 'Save product'}</Button></header>
        {groups.length === 0 && <p className="rounded-lg border p-4">Create a product group first. <Link href={index()} className="underline">Manage groups</Link></p>}
        {currencies.length === 0 && <p className="rounded-lg border p-4">Configure a billing currency before creating products.</p>}
        {form.recentlySuccessful && <p role="status" className="rounded-lg bg-muted p-3 text-sm">Product saved. Changes apply to new orders; existing order prices and services are preserved.</p>}
        {form.hasErrors && <div role="alert" className="rounded-lg border border-destructive p-4 text-sm text-destructive"><p className="font-medium">Please correct these fields:</p><ul className="mt-2 list-inside list-disc">{Object.entries(errors).map(([field, message]) => <li key={field}>{message}</li>)}</ul></div>}
        <nav className="flex gap-2 border-b pb-3" aria-label="Product sections">{['details', 'pricing', 'provisioning'].map(section => <Button key={section} type="button" variant={tab === section ? 'default' : 'ghost'} aria-pressed={tab === section} onClick={() => setTab(section)} className="capitalize">{section}</Button>)}</nav>
        <section hidden={tab !== 'details'} className="space-y-6"><div className="grid gap-5 md:grid-cols-2">
            <div className="space-y-2"><Label htmlFor="name">Product name</Label><Input id="name" required value={form.data.name} onChange={e => form.setData('name', e.target.value)} /></div>
            <div className="space-y-2"><Label htmlFor="slug">Slug</Label><Input id="slug" required placeholder="business-hosting" value={form.data.slug} onChange={e => form.setData('slug', e.target.value)} /></div>
            <div className="space-y-2"><Label htmlFor="group">Product group</Label><select id="group" className={selectClass} value={form.data.product_group_id} onChange={e => form.setData('product_group_id', e.target.value)}>{groups.map(group => <option key={group.id} value={group.id}>{group.name}</option>)}</select></div>
            <div className="space-y-2"><Label htmlFor="type">Product type</Label><select id="type" className={selectClass} value={form.data.type} onChange={e => form.setData('type', e.target.value)}>{[['shared_hosting','Shared hosting'],['reseller_hosting','Reseller hosting'],['vps','VPS / server'],['custom','Other service']].map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></div>
        </div><div className="space-y-2"><Label htmlFor="description">Description</Label><textarea id="description" className="min-h-32 w-full rounded-lg border bg-background p-3" value={form.data.description} onChange={e => form.setData('description', e.target.value)} /></div>
        <div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="sort">Display order</Label><Input id="sort" type="number" min="0" value={form.data.sort_order} onChange={e => form.setData('sort_order', Number(e.target.value))} /></div><div className="space-y-3">{[['is_active','Available to order'],['is_visible','Visible in storefront'],['requires_domain','Require an existing domain']].map(([field,label]) => <label key={field} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.data[field as 'is_active' | 'is_visible' | 'requires_domain']} onChange={e => form.setData(field as 'is_active' | 'is_visible' | 'requires_domain', e.target.checked)} />{label}</label>)}</div></div></section>
        <section hidden={tab !== 'pricing'} className="space-y-5"><div className="max-w-sm space-y-2"><Label htmlFor="billing-type">Payment type</Label><select id="billing-type" className={selectClass} value={form.data.billing_type} onChange={e => paymentType(e.target.value)}><option value="recurring">Recurring</option><option value="one_time">One time</option><option value="free">Free</option></select></div><p className="text-sm text-muted-foreground">{form.data.billing_type === 'free' ? 'Free products have no invoice, setup fee, or renewal date.' : 'Add the currencies and billing cycles you offer. Omitted combinations will not be available to order. Setup fees apply only to the initial order.'}</p>
        <div className="space-y-3">{form.data.pricing.map((price,row) => <div key={row} className="grid items-end gap-3 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-5"><div className="space-y-2"><Label htmlFor={`currency-${row}`}>Currency</Label><select id={`currency-${row}`} className={selectClass} value={price.currency_id} onChange={e => setPrice(row,'currency_id',e.target.value)}>{currencies.map(c => <option key={c.id} value={c.id}>{c.code}</option>)}</select></div><div className="space-y-2"><Label htmlFor={`cycle-${row}`}>Cycle</Label><select id={`cycle-${row}`} className={selectClass} value={price.billing_cycle} onChange={e => setPrice(row,'billing_cycle',e.target.value)}>{(form.data.billing_type === 'recurring' ? recurring : ['one_time']).map(cycle => <option key={cycle} value={cycle}>{cycle.replaceAll('_', ' ')}</option>)}</select></div><div className="space-y-2"><Label htmlFor={`price-${row}`}>Price</Label><Input id={`price-${row}`} type="number" min="0" step="0.01" disabled={form.data.billing_type === 'free'} value={price.price} onChange={e => setPrice(row,'price',e.target.value)} /></div><div className="space-y-2"><Label htmlFor={`setup-${row}`}>Setup fee</Label><Input id={`setup-${row}`} type="number" min="0" step="0.01" disabled={form.data.billing_type === 'free'} value={price.setup_fee} onChange={e => setPrice(row,'setup_fee',e.target.value)} /></div><Button type="button" variant="outline" disabled={form.data.pricing.length === 1} onClick={() => form.setData('pricing',form.data.pricing.filter((_,i) => i !== row))}>Remove</Button></div>)}</div><Button type="button" variant="outline" onClick={() => form.setData('pricing',[...form.data.pricing,{currency_id:String(currencies[0]?.id ?? ''),billing_cycle:form.data.billing_type === 'recurring' ? 'monthly':'one_time',price:'0.00',setup_fee:'0.00'}])}>Add currency / cycle</Button></section>
        <section hidden={tab !== 'provisioning'} className="space-y-6"><div className="max-w-sm space-y-2"><Label htmlFor="module">Provisioning module</Label><select id="module" className={selectClass} value={form.data.module} onChange={e => form.setData('module',e.target.value)}><option value="manual">No external module</option><option value="enhance">Enhance hosting</option></select></div>
        {form.data.module === 'enhance' && <div className="space-y-4 rounded-xl border p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Enhance package</h2><Button type="button" variant="outline" disabled={loading || nextPage === null} onClick={loadPlans}>{loading ? 'Loading…' : remotePlans.length ? nextPage ? 'Load more plans' : 'Plans loaded' : 'Load plans from Enhance'}</Button></div><InputError message={planError} />{remotePlans.length > 0 && <select aria-label="Choose an Enhance plan" className={selectClass} value={form.data.plan_id} onChange={e => form.setData('plan_id',e.target.value)}><option value="">Select a plan</option>{remotePlans.map(plan => <option key={plan.id} value={plan.id}>{plan.name} (#{plan.id})</option>)}</select>}<div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="plan">Plan ID</Label><Input id="plan" type="number" min="1" value={form.data.plan_id} onChange={e => form.setData('plan_id',e.target.value)} /></div><div className="space-y-2"><Label htmlFor="server">Application server UUID (optional)</Label><Input id="server" value={form.data.app_server_id} onChange={e => form.setData('app_server_id',e.target.value)} placeholder="Use the Enhance plan’s default placement" /></div></div><p className="text-sm text-muted-foreground">Uses your configured Enhance panel. Only shared hosting website provisioning is currently supported by this module.</p></div>}
        <fieldset className="space-y-3"><legend className="mb-3 font-semibold">When should this product be activated?</legend>{setupModes.map(([value,label,description]) => <label key={value} className="flex cursor-pointer items-start gap-3 rounded-lg border p-4"><input type="radio" name="setup_mode" value={value} checked={form.data.setup_mode === value} onChange={e => form.setData('setup_mode',e.target.value)} className="mt-1" /><span><span className="font-medium">{label}</span><span className="mt-1 block text-sm text-muted-foreground">{description}</span></span></label>)}</fieldset></section>
        <footer className="flex items-center justify-between border-t pt-5">{product ? <Button type="button" variant="destructive" onClick={() => setDeleting(true)}>Delete product</Button> : <span />}<Button disabled={form.processing || !groups.length || !currencies.length}>Save product</Button></footer>
    </form><Dialog open={deleting} onOpenChange={setDeleting}><DialogContent><DialogHeader><DialogTitle>Delete this product?</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Products with orders or services cannot be deleted. Disable availability to stop new orders while keeping billing history.</p><InputError message={errors.product} /><Button variant="destructive" disabled={form.processing} onClick={() => { if (product) { form.delete(destroy.url(product.id)); } }}>Delete product</Button></DialogContent></Dialog></>;
}
